### PR TITLE
tweaks to make it work with Eclipse

### PR DESCRIPTION
**Pull request by uschmidt83**

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
Hey @uschmidt83,

thanks for the PR, but (as I figured out yesterday) kapt is unfortunately needed to correctly process the SciJava annotations required to recognize this as a plugin. Is it recognized for you correctly after removing this?

cheers!

**Comment by uschmidt83** [comment]
Yes, works fine for me in Eclipse (Neon.3 Release (4.6.3)).

**Comment by uschmidt83** [comment]
If I leave kapt in there, I get an error when I import the Maven project into Eclipse.

**Comment by skalarproduktraum** [comment]
What's the error specifically? I had the issue that _without kapt_, neither Maven nor IntelliJ would create the needed JSON file correctly...

**Comment by uschmidt83** [comment]
error

**Comment by uschmidt83** [comment]
I just talked to Curtis about this. Stay tuned.

**Comment by skalarproduktraum** [comment]
Thank you :)

**Comment by uschmidt83** [comment]
It should now work with Eclipse and Maven. Does it work in IntelliJ?
If so, we should check if mixed Java and Kotlin sources work together.

**Pull request merged**
